### ISSUE TITLE
Large and XLarge column spans use 12 columns but should be 16 columns & Angular export doesn't export col span

### ISSUE THREAD

**Issue by gcate** [IBM/carbon-ui-builder#111]
In **builder**
Large and XLarge column spans use 12 columns but should be 16 columns (reference [carbon grid guidelines](https://carbondesignsystem.com/guidelines/2x-grid/overview/))
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/4819973/176544168-0bed633b-cff7-4841-8895-cd47dcf3dffa.png">

React **export** also uses the 12 columns
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/4819973/176543989-d076b09f-81eb-4d2b-b0e7-dca0e352d628.png">

Angular **export** doesn't export the col span settings
<img width="1697" alt="image" src="https://user-images.githubusercontent.com/4819973/176543914-6f8ecc2c-3b17-4c2d-a9a2-78a0f25fa242.png">

If I use  react to prototype the same thing, the col spans act correctly 
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/4819973/176544008-c429983b-88f5-4934-9e82-5284cd18b100.png">

JSON here
[TestColumnSpan.json.zip](https://github.com/IBM/carbon-components-builder/files/9014348/TestColumnSpan.json.zip)

**Comment by zvonimirfras** [comment]
Large and XLarge go to 16 in the UI at the moment. Is that it, @gcate?
![image](https://user-images.githubusercontent.com/9692126/184230061-2328da51-f968-4c2b-a11d-d0fc5315d177.png)

**Comment by gcate** [comment]
No, the issue is the display.  In UI builder if I create 16 columns, each with large span 1,  the columns wrap after 12. But Carbon grid is 16 columns.  UI builder should wrap after 16 columns. 
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/4819973/184510491-901e637b-228e-4de0-9f04-5ca36f90f0d7.png">

**Comment by zvonimirfras** [comment]
I think this is covered since we moved to Carbon v11. If something is missing, please open separate issues.
