### ISSUE TITLE
List of components missing in builder

### ISSUE THREAD

**Issue by MoizMasud** [IBM/carbon-ui-builder#120]
- [x] Content switcher -- moiz
- [ ] Data table * (basic)
- [ ] Date picker --moiz
- [ ] File uploader * -- moiz
- [x] Inline loading --Moiz
- [ ] Modal * -
- [ ] Notification - Moiz
- [ ] Pagination * -- Moiz
- [ ] Popover v11
- [ ] Progress bar v11
- [ ] Select * -- moiz
- [ ] Slider * - Moiz
- [ ] Structured list * (basic)
- [ ] Tabs -- moiz
- [ ] Toggletip v11
- [ ] Tooltip --Moiz

**Comment by Akshat55** [comment]
Popover, Progress bar, Toggletip are Carbon v11 components.

If we are running carbon v11 alongside v10 (from pal), start (build) time will be long 🤔

**Comment by Hardik-RJ** [comment]
individual tickets are open for each component.
