### ISSUE TITLE
Unable to recognize "GENERATE_SOURCEMAP" on npm start

### ISSUE THREAD

**Issue by coder-cell** [IBM/carbon-ui-builder#127]
Hi,
I am facing an issue with the `npm start`, where it throws an error _ unable to recognize GENERATE_SOURCEMAP_.

_'GENERATE_SOURCEMAP' is not recognized as an internal or external command,
operable program or batch file._

![image](https://user-images.githubusercontent.com/58884543/180247019-00706b38-1d70-4c53-a8e3-4fc708db8b16.png)

Nodejs version : v16.4.2

**Comment by zvonimirfras** [comment]
Hi Mani.

> **You DO NOT NEED to do all this just to use the builder.**
> **Head over to https://builder.carbondesignsystem.com/ instead.**
> 
> **This is the process you need to go if you're looking to contribute.**

_With that out of the way..._

`GENERATE_SOURCEMAP` is indeed not a command, it's a shell variable set to `false`.

If you used `bash` (using Windows subsystem for Linux or some other way), this would work.

You should be able to delete `GENERATE_SOURCEMAP=false` from package.json start command to run it (with a slightly modified experience).
