### ISSUE TITLE
"Toggle" commponent react export doesn't update state

### ISSUE THREAD

**Issue by zvonimirfras** [IBM/carbon-ui-builder#135]
React exports need to update state on user interaction, to make it easier for the devs to use the component in their apps.

[Checkbox](https://github.com/IBM/carbon-ui-builder/blob/main/src/fragment-components/a-checkbox.tsx) is the most similar component to [Toggle](https://github.com/IBM/carbon-ui-builder/blob/main/src/fragment-components/a-toggle.tsx) and Toggle's changes should be handled in a similar way.

**Comment by prasoonmhwr** [comment]
@zvonimirfras can you please add some detail/description to it :)

**Comment by zvonimirfras** [comment]
@prasoonmhwr ah, yes, context 😅 

Added!

Wanna take a stab at it, Prasoon?

**Comment by prasoonmhwr** [comment]
> @prasoonmhwr ah, yes, context 😅 
> 
> Added!
> 
> Wanna take a stab at it, Prasoon?

Yes please 🙂

**Comment by prasoonmhwr** [comment]
@zvonimirfras after running npm install and npm start my terminal is stuck at this

<img width="1135" alt="Screenshot 2022-10-15 at 9 44 12 AM" src="https://user-images.githubusercontent.com/52622674/195968260-42bf5a76-c674-4b61-abe7-6b330a77bdc4.png">


And browser is also a blank screen at localhost:3000

any ideas what could be the issue

**Comment by prasoonmhwr** [comment]
@zvonimirfras  Is this the desired behaviour

## Current Implementation

<img width="1075" alt="Screenshot 2022-10-15 at 1 02 41 PM" src="https://user-images.githubusercontent.com/52622674/195975117-80f23876-b183-4a9b-827d-93179129b329.png">


## Previous Implementation

<img width="1071" alt="Screenshot 2022-10-15 at 1 02 07 PM" src="https://user-images.githubusercontent.com/52622674/195975129-120a4d5a-5e65-44b4-8268-6e6ae6077d04.png">

**Comment by zvonimirfras** [comment]
@prasoonmhwr On the first look, that might be it!

You can test the exported code on code sandbox by clicking on "Edit on code sandbox" link above and to the right of the code frame 😉

**Comment by prasoonmhwr** [comment]
@zvonimirfras this is it right? Or Am i Missing something


https://user-images.githubusercontent.com/52622674/195987440-32b01b95-4ba9-46e0-ab9a-9f24487fe29e.mp4

**Comment by zvonimirfras** [comment]
Looks right, submit the PR and let's see the code 🚀

**Comment by prasoonmhwr** [comment]
Here it is https://github.com/IBM/carbon-ui-builder/pull/165
