### ISSUE TITLE
New Fragment Screen Should Use Radio Buttons

### ISSUE THREAD

**Issue by kennethreyna-IBM** [IBM/carbon-ui-builder#145]
<img width="858" alt="Screen Shot 2022-08-27 at 9 00 39 PM" src="https://user-images.githubusercontent.com/112298402/187056748-5bcd0516-08cc-496c-905c-e33f66045392.png">

The Carbon UI Builder "New Fragment" dialog should use Radio Button instead of current checkbox (see attached).

**Comment by Yaswanth820** [comment]
Hey @kennethreyna-IBM . I want to work on this issue.
Can you please assign this to me under `hacktoberfest`?

**Comment by kennethreyna-IBM** [comment]
@zvonimirfras I don't have the ability to assign bugs. Do you have that ability? If so, can you assign this one to @Yaswanth820 in the way he asks above? Thanks!

**Comment by zvonimirfras** [comment]
@kennethreyna-IBM @Yaswanth820 

Thanks for the ping, Kenny! And thanks for your interest, Balaji!

I'll assign you.

Forewarning, this might not be a straightforward solution that it seems at the surface. Good luck!

_Feel free to reach out to me here, on discord (`Zvonimir#9989`), or anywhere else (I'm easy to find 🙂)_

**Comment by Yaswanth820** [comment]
Thanks @kennethreyna-IBM for helping me to get the issue.
And, Thanks @zvonimirfras for the suggestions. I will try my best to solve the issue.

**Comment by Yaswanth820** [comment]
Hello @zvonimirfras , sorry for the delay.

I have made changes in the code so that the `new fragment` uses `radio buttons` instead of `checkboxes`.

![carbon-ui-issue](https://user-images.githubusercontent.com/55750562/201490685-0e626665-8988-4063-8cd6-f1bfa4e897e6.PNG)

Does it look all ok? Please tell me if there are any improvements.

**Comment by zvonimirfras** [comment]
@Yaswanth820 hi Balaji, is there a PR related to this screenshot?

**Comment by MoizMasud** [comment]
Closing as it was addressed in https://github.com/IBM/carbon-ui-builder/pull/190
