### ISSUE TITLE
Add missing Accordion attributes for Angular

### ISSUE THREAD

**Issue by Akshat55** [IBM/carbon-ui-builder#156]
Add missing attributes added in CCA PR [#2273](https://github.com/IBM/carbon-components-angular/pull/2273), [#2271](https://github.com/IBM/carbon-components-angular/pull/2271)

Referencing #134 to mark Accordion as complete

**Comment by pedroagcf** [comment]
Hey, I can address that

**Comment by Akshat55** [comment]
Great! Thanks for taking this on @pedroagcf, much appreciated 😄 

Just FYI, you'll need to update Angular code output with these two files: 
https://github.com/IBM/carbon-ui-builder/tree/main/src/fragment-components/accordion

**Comment by Akshat55** [comment]
Hi @pedroagcf, are you still able to work on this issue? Please let me know if you need any assistance!

**Comment by Akshat55** [comment]
I'm unassigning @pedroagcf and removing the `hacktoberfest` tag. 

@MoizMasud, would you like to take this issue on?
