### ISSUE TITLE
I want to add dark mode to light mode and vice versa button

### ISSUE THREAD

**Issue by ApoorvShri** [IBM/carbon-ui-builder#162]

**Comment by zvonimirfras** [comment]
Hi @ApoorvShri, how would you go about doing that?

**Comment by ApoorvShri** [comment]
We can add a button with sliding effect on the navbar to change the mode

**Comment by zvonimirfras** [comment]
@ApoorvShri I understood that part. I'm curious about the implementation. :slightly_smiling_face:

**Comment by zvonimirfras** [comment]
Feel free to reopen if needed.
