### ISSUE TITLE
I want to add footer

### ISSUE THREAD

**Issue by ApoorvShri** [IBM/carbon-ui-builder#163]

**Comment by zvonimirfras** [comment]
Hi @ApoorvShri, thanks for your interest. What kind of a footer did you have in mind and what would you put into it?

**Comment by ApoorvShri** [comment]
We can add copyright, GitHub repo, social links and contact info

**Comment by zvonimirfras** [comment]
Based on the nature and current design of the app, I don't think we're going to have a need for it at the moment.

Appreciate the suggestion tho. :slightly_smiling_face:
