### ISSUE TITLE
[Fix] Fragment Delete Modal Notification is behind the header

### ISSUE THREAD

**Issue by Dexters-Hub** [IBM/carbon-ui-builder#168]
Hi @zvonimirfras 👋🏻 

I was just testing out the Carbon UI Builder and found the existing Featured Fragment. I opened it to see, what it was and made my own fragment, and  I navigated back to All Fragments.  Then found the Simple Form Copy, then I deleted that. Then the Fragment Delete Modal Notification pop-up and the issue were noticed.

I would like to contribute to the project by looking at this issue.

[Fragment Delete Modal](https://github.com/IBM/carbon-ui-builder/blob/adb91f317f3ae9e0964b60d2d4ca55a9b3fffa60/src/routes/edit/fragment-delete-modal.tsx)

![Screenshot from 2022-10-17 20-36-46](https://user-images.githubusercontent.com/47777599/196215274-a80d2f5c-f84c-4150-80c7-00416a5aeef3.png)

If you could assign this to me, It would be really great. 

Thank you 😄

**Comment by zvonimirfras** [comment]
Sure thing, John (@Dexters-Hub), assigned!
