### ISSUE TITLE
suggestion: issue/pr template

### ISSUE THREAD

**Issue by sadiejay** [IBM/carbon-ui-builder#173]
Problem:
- Currently, there are no guidelines for what information issues and pull requests should contain. This adds ambiguity for contributors on what to include when submitting issues / prs and adds more time and mental burden for maintainers when understanding why or how a contribution could be considers.

Proposed solution:
- I suggest creating an action by adding yml files to the .github directory that automatically formats incoming issues and prs with desired information that maintainers would like to know and to guide contributors to adding helpful information about their issue/pr.
- The action could be as robust as creating a landing page to different types of issue templates, automatically labeling issues and closing prs or as simple as sections with headings informing contributors what information to include.

Additional Resources:
- Examples:
  - Virtual Coffee repo — https://github.com/Virtual-Coffee/virtualcoffee.io/issues/new/choose
  - Open Sauced docs repo — https://github.com/open-sauced/docs.opensauced.pizza/issues/new/choose
  - A Call for Code repo — https://github.com/Call-for-Code-for-Racial-Justice/Incident-Accuracy-Reporting-System/blob/main/.github/pull_request_template.md
  
I would be happy to be assigned to this issue, if it is something I can work on :)

**Comment by zvonimirfras** [comment]
Sounds good, Sadie (@sadiejay)!

I see from examples that they are very custom.
What do you think would be good options for this repo?

**Comment by sadiejay** [comment]
Looking at the repo it seems that the most used tags issues are "enhancement," "bug," and "discussion." 

I think new issues could be categorized as "enhancement"(new feature requests) and "bug," while also providing the blank issue option.  

Depending on the triage system of tagging, discussion could be tagged manually for applicable issues or we could create a dedicated "discussion" issue as well. 

What do you think?
