### ISSUE TITLE
Code snippet bug

### ISSUE THREAD

**Issue by MoizMasud** [IBM/carbon-ui-builder#218]
### Current Behavior

Unable to type in monaco editor

**Comment by zvonimirfras** [comment]
@MoizMasud Which one?

You're not supposed to be able to type in exports, for example.

**Comment by MoizMasud** [comment]
<img width="293" alt="Screenshot 2023-01-24 at 6 30 32 PM" src="https://user-images.githubusercontent.com/23690711/214444113-262d5014-730b-4135-8617-769a1a81ee2a.png">

**Comment by MoizMasud** [comment]
@zvonimirfras the code section in Code Snippet
