### ISSUE TITLE
No Spacing blocks included in the Elements set.

### ISSUE THREAD

**Issue by kunderwoodatadaptive** [IBM/carbon-ui-builder#233]
I have been playing around in the UI builder and notice that, while Spacing blocks are included in the Figma files, there are none in the Elements set on the UI Builder.

That's been posing a tricky problem for creating vertical spacing on my Fragment. Do you have insight or any plans to include this feature?

**Comment by zvonimirfras** [comment]
Hi @kunderwoodatadaptive!

You can achieve spacing using the Layout widget below the General settings.

Click the component you want to add spacing next to then set margin or padding on any side. Margin is spacing on the outside of the component. Padding is spacing on the inside of the component.

For a button this looks like:

![image](https://user-images.githubusercontent.com/9692126/224340003-deff7b06-d2c5-469c-8c9d-48478b949171.png)

And results in:

![image](https://user-images.githubusercontent.com/9692126/224347734-746749d3-9f5b-4d26-b929-6fc53ef79e77.png)

 Notice the spacing before the button and inside the button before text.

Is there any use-case this doesn't cover but a spacer component would?
