### ISSUE TITLE
Many Angular carbon UI components do not export properly into CodeSandBox 

### ISSUE THREAD

**Issue by dirkknibbe** [IBM/carbon-ui-builder#240]
https://www.loom.com/share/c85bf4e3851e404abf7b665f2df6b355

## Issue happening with items:
Accordion
Bread Crumb
Button
Checkbox
Code Snippet
Content Switcher
Dropdown
Grid
Inline Loading
Link
Loading
Progress Indicator
Search
Tag
Toggle

**Comment by zvonimirfras** [comment]
Thanks for reporting this, Dirk!

It's because fragments have the same names as existing components so the builder creates a clashing module name 🤔 

@MoizMasud can you look into this?
