### ISSUE TITLE
Replace CodeSandbox link with Stackblitz link

### ISSUE THREAD

**Issue by zvonimirfras** [IBM/carbon-ui-builder#274]
For reasons we're not getting into here, CodeSandbox doesn't correctly render Carbon 11 styles for users who are not logged in.
This makes the "Edit on CodeSandbox" link useless to users at the moment. It's still a nice feature to have so we should replace it with Stackblitz, which works correctly.

We're talking about the link in the export modal (you get to it through the edit screen by clicking "Export" button)

<img width="512" alt="image" src="https://github.com/IBM/carbon-ui-builder/assets/9692126/dae94677-4d56-486b-9f44-b3380f86e178">

In code this lives in the export-modal.tsx

**Comment by zvonimirfras** [comment]
Sure!

**Comment by RajuGangitla** [comment]
@zvonimirfras i integarted stackBlitz when i click on buuton its going to stackblitz after installing packages its saying throwing this error 
Error in src/app/components/new-fragment/new-fragment.module.ts
The entrypoint for 'carbon-components-angular' could not successfully be resolved. The file '/turbo_modules/carbon-components-angular@5.14.10/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.

**Comment by Akshat55** [comment]
Hey @RajuGangitla could you provide some more context on this issue? Perhaps, could you include a link to the stackblitz so we can verify for ourselves if there are any configuration issues?

**Comment by RajuGangitla** [comment]
@Akshat55 https://stackblitz.com/edit/angular-w88xpr?file=src%2Fapp%2Fapp.component.ts

**Comment by RajuGangitla** [comment]
@Akshat55 any update on this

**Comment by Akshat55** [comment]
Thanks for the link, seems like there is a platform issue where it cannot detect the index file that has all of the exports. I've noticed this being reported on multiple angular project. I do have a workaround but it isn't recommended.


We don't have a solution for this and the team will have to determine the best way around this issue.

**Comment by RajuGangitla** [comment]
@Akshat55 can u assign the other issue to me

**Comment by Akshat55** [comment]
I've assigned you the issue @RajuGangitla

**Comment by RajuGangitla** [comment]
Ok

**Comment by zvonimirfras** [comment]
Looks like at the moment there's no good solution for this due to incompatibilities with carbon v11
