### ISSUE TITLE
*404: Not found* when trying to export

### ISSUE THREAD

**Issue by Donnz** [IBM/carbon-ui-builder#285]
### Current Behavior

After editing a template, I click on "Export" button and the page falls on "404" status. This is happening on any fragment that I try to export.

### Steps To Reproduce

Open a fragment
Click on export

### Expected Behavior

Open the export modal

### What browsers are you seeing the problem on?

Firefox

### Environment

MacOS Sonoma 14.0
Firefox developer edition 120.0b2 (64-bits)

### Additional resources

https://github.com/IBM/carbon-ui-builder/assets/6741031/84abc8dc-d96a-4cac-a28e-aa5d22e9b615

**Comment by zvonimirfras** [comment]
Thanks for reporting, Wallace (@Donnz)!

I think this was resolved. Please, reopen if still an issue!
