### ISSUE TITLE
Carbon Builder Loads a Blank Screen with a JS error logged to console in Chrome and Chromium based Edge, Loads Fine in Firefox

### ISSUE THREAD

**Issue by memtech3** [IBM/carbon-ui-builder#303]
### Current Behavior

Carbon Builder loads a blank screen, throws error `index-335f3d19.js:2599 Uncaught SyntaxError: Invalid or unexpected token (at index-335f3d19.js:2599:8622)` in dev tools console in chrome browser. Loads fine in firefox.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Environment

Operating System: 
Browser Version: Chrome 123.0.6312.86 (Official Build) (64-bit) (cohort: Stable) 
Browser Revision: 9b72c47a053648d405376c5cf07999ed626728da-refs/branch-heads/6312@{#698}
Operating System: Windows 11 Version 23H2 (Build 22631.3296)
Browser JavaScript: V8 12.3.219.14

**Comment by zvonimirfras** [comment]
This seems to be related to a cloudflare issue and should be solved now. Please reopen if needed.
