### ISSUE TITLE
Prevent drag & drop of specific components

### ISSUE THREAD

**Issue by Akshat55** [IBM/carbon-ui-builder#63]
Need an option to prevent drag & dropping of specific components.

Ex. `TileBelowTheFoldContent` component (Part of expandable tiles), should not be allowed to be dragged/dropped outside of expandable tile. 

In some scenarios, it might be better to display a notification instead of completely preventing them from dragging and dropping the component.

**Comment by zvonimirfras** [comment]
This should be possible to do now with d7adaae and d9fc829

See 98a6c35 and 3a38e0f for examples.

cc @Akshat55
