### ISSUE TITLE
Accordion functionality is not working after exporting on UI

### ISSUE THREAD

**Issue by sushama20** [IBM/carbon-ui-builder#84]
Accordion is not getting displayed after exporting on UI

On fragment accordion is visible
<img width="874" alt="acc_design" src="https://user-images.githubusercontent.com/43578026/169748434-027db22c-735f-4863-80ae-57a1b2237dcd.png">

On UI, it directly shows accordion content without the down arrow and header of accordion item
<img width="1490" alt="UI_accordian" src="https://user-images.githubusercontent.com/43578026/169748504-06b229dc-34d0-4ada-8b6f-854495243044.png">

**Comment by zvonimirfras** [comment]
Tested a few layouts and seems to be working fine in codesandbox.

What are the steps to replicate this?
